site_name: WhatsOpt
nav:
  - Home: index.md
  - Installation: install.md
  - Architecture: architecture.md
  - Administration: administration.md
  - Contributing: contrib.md
  - About: about.md
theme: 
  name: readthedocs
  language: en
markdown_extensions:
  - admonition
repo_url: https://github.com/OneraHub/WhatsOpt-Doc

